Lesson 6
namelexa/kalexey pull request #7
Opened 2018-12-02 18:19 UTC by namelexa

### Description

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title
2. ...

### Manual testing scenarios

1. ...
2. ...

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-12-03 22:11 UTC, maksymz requested changes

2018-12-03 22:11 UTC, maksymz commented on app/code/AKisilenko/ModuleLesson6/view/frontend/web/js/ask-question.js
> +            return $(this.element).validate().valid();
Validation does not work because of this. Please, refer to Lesson 6 code to fix this.

2018-12-03 22:11 UTC, maksymz commented on app/code/AKisilenko/ModuleLesson6/view/frontend/web/js/ask-question.js
> +                        $.mage.cookies.set(self.options.cookieName, self.options.cookieName, {expires: date});
Use `lifetime` parameter instead of working with dates and using `expires`. Refer to the $.mage.cookies widget code.

2018-12-03 22:11 UTC, maksymz commented on app/code/AKisilenko/ModuleLesson6/view/frontend/web/js/ask-question.js
> +            if (!this.validateForm()) {
Cookie should be checked before sending form. DO not send data if the cookie is still present in 120 seconds.

2018-12-03 22:11 UTC, maksymz commented on app/code/AKisilenko/ModuleLesson6/view/frontend/requirejs-config.js
> +            'validation': 'mage/validation/validation'
No need to override default Magento code

2018-12-03 22:11 UTC, maksymz commented on app/code/AKisilenko/ModuleLesson6/Controller/Submit/Index.php
> +                $data = [
Should throw exception here like in the previous `if` statements

2018-12-04 12:24 UTC, namelexa commented on app/code/AKisilenko/ModuleLesson6/view/frontend/web/js/ask-question.js
> +            return $(this.element).validate().valid();
fixed
return $(this.element).validation().valid();

2018-12-04 12:25 UTC, namelexa commented on app/code/AKisilenko/ModuleLesson6/view/frontend/web/js/ask-question.js
> +                        $.mage.cookies.set(self.options.cookieName, self.options.cookieName, {expires: date});
It was done with `lifetime` parameter

2018-12-04 12:27 UTC, namelexa commented on app/code/AKisilenko/ModuleLesson6/view/frontend/web/js/ask-question.js
> +            if (!this.validateForm()) {
I added a form check before submitting the form.

2018-12-04 12:28 UTC, namelexa commented on app/code/AKisilenko/ModuleLesson6/view/frontend/requirejs-config.js
> +            'validation': 'mage/validation/validation'
It was an experiment of something, I do not even remember what :) Already deleted

2018-12-04 12:29 UTC, namelexa commented on app/code/AKisilenko/ModuleLesson6/Controller/Submit/Index.php
> +                $data = [
All done

2018-12-08 14:51 UTC, maksymz commented on app/code/AKisilenko/ModuleLesson6/Controller/Submit/Index.php
> +                $data = [
Not completed... Don't see any exception statements here like `throw new LocalizedException`

2018-12-08 14:52 UTC, merged