Lesson 9
namelexa/kalexey pull request #9
Opened 2018-12-14 10:31 UTC by namelexa

### Description

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title
2. ...

### Manual testing scenarios

1. ...
2. ...

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2019-01-09 09:49 UTC, APanteleychuk requested changes
Need fix

2019-01-09 09:49 UTC, APanteleychuk commented on app/code/AKisilenko/ModuleLesson9/view/frontend/templates/widget/homepagebanner.phtml
> +        background: <?php echo $block->getData('button_color') ?>;
- styles need use in css file or use inline style
- use set/get methods like getButtonColor()

2019-01-09 09:49 UTC, APanteleychuk commented on app/code/AKisilenko/ModuleLesson9/view/frontend/templates/widget/homepagebanner.phtml
> +            ->createBlock('Magento\Cms\Block\Block')
This functionality need move in block class like function

2019-01-09 09:49 UTC, APanteleychuk commented on app/code/AKisilenko/ModuleLesson9/view/frontend/templates/widget/homepagebanner.phtml
> +            <?php echo $block->getData('button_title') ?>
- Use set/get magic method 
- onclick is bad decision, use <a class="button" href ....

2019-01-09 10:29 UTC, APanteleychuk requested changes

2019-01-09 10:29 UTC, APanteleychuk commented on app/code/AKisilenko/ModuleLesson9/etc/widget.xml
> +        <containers>
`<containers>  
<container..`
-  it's not needed

2019-01-09 14:19 UTC, APanteleychuk requested changes

2019-01-09 14:19 UTC, APanteleychuk commented on app/code/AKisilenko/ModuleLesson9/view/frontend/templates/widget/homepagebanner.phtml
> +           style="background: <?php echo $block->getData('button_color') ?>;">
Use set/get magic method like $block->getButtonColor()

2019-01-09 14:19 UTC, APanteleychuk commented on app/code/AKisilenko/ModuleLesson9/view/frontend/templates/widget/homepagebanner.phtml
> +        <a href="geekhub-cms" class="button-homepage"
href="geekhub-cms" - it's wrong, need use $block->getUrl('geekhub-cms')

2019-01-09 14:19 UTC, APanteleychuk commented on app/code/AKisilenko/ModuleLesson9/view/frontend/templates/widget/homepagebanner.phtml
> +        <?php echo $block->getHomeBanner(); ?>
no check if block no exist

2019-01-09 15:51 UTC, APanteleychuk requested changes

2019-01-09 15:51 UTC, APanteleychuk commented on app/code/AKisilenko/ModuleLesson9/view/frontend/templates/widget/homepagebanner.phtml
> +            <?php if ($block->getData('button_title')) : ?>
why you don't use set/get methods here and ather places?

2019-01-11 09:28 UTC, namelexa commented on app/code/AKisilenko/ModuleLesson9/view/frontend/templates/widget/homepagebanner.phtml
> +            <?php if ($block->getData('button_title')) : ?>
all done

2019-01-16 19:17 UTC, merged